# Generated by Django 5.1.6 on 2025-11-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postalcode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
