# Generated by Django 5.1.6 on 2025-09-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='cart_product',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cart_product',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Cart_product',
        ),
    ]
