# Generated by Django 5.1.6 on 2025-03-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard', '0002_alter_cart_owner_alter_cart_product_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_product',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
