# Generated by Django 5.1.6 on 2025-10-02 19:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard', '0002_remove_cart_owner_remove_cart_product_cart_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcomment',
            unique_together={('product', 'owner')},
        ),
    ]
