# Generated by Django 5.1.6 on 2025-11-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
