# Generated by Django 5.1.6 on 2025-06-18 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard', '0009_alter_productcomment_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingStar',
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
