# Generated by Django 5.1.6 on 2025-06-18 21:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard', '0010_delete_ratingstar_alter_productcomment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
